### ISSUE TITLE
Has a Chinese localization team already started this work？

### ISSUE THREAD

**Issue by eventhorizonsky** [TwnKey/YCTT#1]
请问YS I和YS II目前有团队正在进行中文化翻译吗，如果有的话，团队是否需要帮忙？

May I ask if there is currently a team working on translating Chinese culture between YS I and YS II?
 If so, does the team need any help?

**Comment by TwnKey** [comment]
Hello,

Some chinese people were interested in translating it, but I think they gave up (I was told nobody is working on it right now).

**Comment by eventhorizonsky** [comment]
Thank you very much. I tried to use your tool to translate through GPT for technical testing, which seems to be very effective (of course, the translation effect has not reached the level that can be released), I will use the results of this technical test to find partners willing to participate in this matter, thank you very much for your tool
