### ISSUE TITLE
Diary and conversation seem to require two sets of text.ini

### ISSUE THREAD

**Issue by eventhorizonsky** [TwnKey/YCTT#2]
Hello, We have discovered that the diary text seems to use the FONT.SKI font file, which requires a separate text.ini file to match the characters. However, the YsIIScenaTool currently appears to only support a single ini file to generate the ys2_libre.ys2 file. We would like to ask you how to make the characters of both the diary and the dialogue text compatible simultaneously.

**Comment by TwnKey** [comment]
Just to be sure I understand, the diary is also in ys2_libre? Which leads to the game using a different font for the diary that do not match the encoding decided for the other font?

So ideally what I need is to detect with the tool what are the lines used in the diary specifically, and let the user provide a text ini for the diary?

If so i can try to see what can be done during this week

**Comment by eventhorizonsky** [comment]
Yes, the diary content is also in ys2_libre and uses a different SKI file. I am not sure if the following information will be helpful: when using the original FONT.SKI, parts of the text in the diary appear as underlined. When I try to convert only the FONT.SKI without replacing ys2_libre (the generated text.ini in this case is different from the one generated by FONT16.SKI), the text in the diary becomes almost completely abnormal.

**Comment by TwnKey** [comment]
Can you try this and let me know if it satisfies you:
https://github.com/TwnKey/YCTT/releases/download/test/YsIIScenaTool.exe

I have added a column in the translation csv, 
![image](https://github.com/TwnKey/YCTT/assets/69110695/4bab315a-2250-4e5c-8888-5a5f493886b3)
where you can specify the .ini file to use for that line (I've tried to automatically detect when it's diary and when it's not, but it is not that simple, hopefully filling the csv is easy enough though).

Let me know.

**Comment by eventhorizonsky** [comment]
Thank you very much. Just now, I found a solution (although I am not sure if it will cause any bugs). I can directly use FONT_16.SKI to generate a new file (or directly specify a new font and size) and then rename this file to FONT.SKI. After repackaging, I found that the text in the diary displayed normally.
I am not sure if this overly simplistic method will cause any problems. I will try using the solution you provided and give you feedback soon.

**Comment by eventhorizonsky** [comment]
This really works! Thank you very much. I'll close this issue.

**Comment by eventhorizonsky** [comment]
I found that if the game is packaged by FONT.SKI and FONT_16.SKI generated from their respective source files, the game will have rendering bugs, as shown in the figure. The reproduction path is [Open diary, switch monster page and return to game page, rendering problem], but if the new FONT.SKI and FONT_16.SKI are all generated from the original FONT_16.SKI file, this problem will not occur.
![image](https://github.com/user-attachments/assets/dc981a73-5ae5-4309-a167-aa88edfd9c20)
